# b.8.60.GRUB-2.06.for.EFI.x64.sh
#
echo "....."
echo "Read the following:"
echo "."
echo "."
echo "Note on freetype2:"
echo "."
echo "Install first freetype2"
echo "then install harbuzz"
echo "then re-install freetype2"
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/which.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/libpng.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/icu.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/libuv.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/cmake.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/harfbuzz.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/freetype2.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/popt.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.2/general/mandoc.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.2/postlfs/efivar.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.2/postlfs/efibootmgr.html"
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "https://ftp.gnu.org/gnu/which/which-2.21.tar.gz"
echo "https://downloads.sourceforge.net/libpng/libpng-1.6.37.tar.xz"
echo "."
echo "https://github.com/unicode-org/icu/releases/download/release-71-1/icu4c-71_1-src.tgz"
echo "https://dist.libuv.org/dist/v1.44.2/libuv-v1.44.2.tar.gz"
echo "https://cmake.org/files/v3.24/cmake-3.24.1.tar.gz"
echo "https://www.linuxfromscratch.org/patches/blfs/11.2/cmake-3.24.1-upstream_fix-1.patch"
echo "https://github.com/harfbuzz/harfbuzz/releases/download/5.1.0/harfbuzz-5.1.0.tar.xz"
echo "."
echo "https://downloads.sourceforge.net/freetype/freetype-2.12.1.tar.xz"
echo "https://downloads.sourceforge.net/freetype/freetype-doc-2.12.1.tar.xz"
echo "."
echo "http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.18.tar.gz"
echo "."
echo "https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz"
echo "https://github.com/rhboot/efivar/releases/download/38/efivar-38.tar.bz2"
echo "."
#echo "https://github.com/rhboot/efibootmgr/archive/18/efibootmgr-18.tar.gz"
echo "https://github.com/rhboot/efibootmgr/releases/download/18/efibootmgr-18.tar.bz2"
echo "."
echo "https://unifoundry.com/pub/unifont/unifont-14.0.04/font-builds/unifont-14.0.04.pcf.gz"
echo "."
echo "."
echo "Be sure the /boot is mounted properly"
echo "."
echo "....."
