# a.08.91.WGet.sh
#
echo "....."
echo "."
echo "."
echo "WGet - for downloading files"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.0/general/libtasn1.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.0/postlfs/p11-kit.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.0/postlfs/make-ca.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.0/basicnet/wget.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.19.0.tar.gz"
echo "https://github.com/p11-glue/p11-kit/releases/download/0.25.0/p11-kit-0.25.0.tar.xz"
echo "https://github.com/lfs-book/make-ca/releases/download/v1.12/make-ca-1.12.tar.xz"
echo "https://ftp.gnu.org/gnu/wget/wget-1.21.4.tar.gz"
echo "."
echo "."
echo "."
echo "....."
