# a.08.80.GRUB-2.06.for.EFI.x64.sh
#
# replacement for 8.60 GRUB for BIOS
#
echo "....."
echo "."
echo "."
echo "miscellaneous - for downloading files"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/basicnet/lynx.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/general/gpm.html"
echo "."
#echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/openssh.html"
#     security
echo "https://www.linuxfromscratch.org/blfs/view/svn/postlfs/openssh.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/general/acpid.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/sudo.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.bz2"
echo "https://www.linuxfromscratch.org/patches/blfs/11.3/lynx-2.8.9rel.1-security_fix-1.patch"
echo "."
echo "https://anduin.linuxfromscratch.org/BLFS/gpm/gpm-1.20.7.tar.bz2"
echo "https://www.linuxfromscratch.org/patches/blfs/11.3/gpm-1.20.7-consolidated-1.patch"
echo "."
#echo"https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.2p1.tar.gz"
echo "https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.3p2.tar.gz"
echo "."
echo "https://downloads.sourceforge.net/acpid2/acpid-2.0.34.tar.xz"
echo "."
echo "https://www.sudo.ws/dist/sudo-1.9.13p1.tar.gz"
echo "."
echo "."
echo "."
echo "....."
