# a.08.80.GRUB-2.06.for.EFI.x64.sh
#
# replacement for 8.60 GRUB for BIOS
#
echo "....."
echo "."
echo "."
echo "WGet - for downloading files"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/general/libtasn1.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/p11-kit.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/make-ca.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.3/basicnet/wget.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.19.0.tar.gz"
echo "https://github.com/p11-glue/p11-kit/releases/download/0.24.1/p11-kit-0.24.1.tar.xz"
echo "https://github.com/lfs-book/make-ca/releases/download/v1.12/make-ca-1.12.tar.xz"
echo "https://ftp.gnu.org/gnu/wget/wget-1.21.3.tar.gz"
echo "."
echo "."
echo "."
echo "....."
