# a.08.80.GRUB-2.06.for.EFI.x64.sh
#
# replacement for 8.60 GRUB for BIOS
#
echo "....."
echo "."
echo "."
echo "GRUB for EFI x64"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/general/popt.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/general/mandoc.html"
echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/efivar.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/efibootmgr.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/11.3/postlfs/grub-efi.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.19.tar.gz"
echo "."
echo "https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz"
echo "https://github.com/rhboot/efivar/releases/download/38/efivar-38.tar.bz2"
echo "."
echo "https://github.com/rhboot/efibootmgr/archive/18/efibootmgr-18.tar.gz"
echo "."
echo "https://unifoundry.com/pub/unifont/unifont-15.0.01/font-builds/unifont-15.0.01.pcf.gz"
echo "."
echo "."
echo "."
echo "....."
